version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t vhanda/ndk-libraries .
      - run:
          name: Build All
          command: docker run -it -v `pwd`/libs/:/root/libs vhanda/ndk-libraries /root/build_all.sh
      - store_artifacts:
          path: libs
          destination: libs
